eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8083/eureka/
server:
  port: 8084
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true