spring:
  datasource:
    url: jdbc:postgresql://monorail.proxy.rlwy.net:47968/railway
    username: postgres
    password: 1ddgD-gCfdcD-3fF623dgae-bGC-G-Cf
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: 8081
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: true
info:
  app:
    name: "Event Microservice"
    description: "Sports App event-microservice Server Application"
    version: "1.0.0"
logging:
  level:
    com:
      sportsApp:
        accounts: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
