spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/event_microservice
    username: postgres
    password: 8434
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/